### PR TITLE
Reverse the order of elif clauses in ast (issue #7)

### PR DESCRIPTION
**Pull request by trotterdylan**
This addressed https://github.com/m-labs/pythonparser/issues/7 for me, although I'm not sure it's the best way. I also wasn't sure how to test this, but I'm happy to add one if I can get a little guidance about what's going on here: https://github.com/m-labs/pythonparser/blob/master/pythonparser/test/test_parser.py#L1380

### CODE REVIEW

**Comment by whitequark** [comment]
assertParseX takes three arguments: the AST (that was squashed into hashes and arrays, to make the code to create it simpler), the code to parse, and the desired location spans. You don't need the last one, so adjusting the https://github.com/m-labs/pythonparser/blob/master/pythonparser/test/test_parser.py#L1398-L1403 part is enough.

**Comment by trotterdylan** [comment]
Alright, updated the existing if/elif/else test to include another elif branch. Confirmed that the test failed before the parser.py change and now passes.

**Comment by whitequark** [comment]
Um, sorry. I meant that you should add another test, just for the elif clause order, and without any location spans (since they're just noise here).

**Comment by trotterdylan** [comment]
Thanks for the info. I added a new assertParsesSuite() without location spans to test_if(). Let me know if you'd rather have a new test method altogether. PTAL

**Pull request merged**
